- name: Check if ble.sh is installed
  shell: command -v ble-update
  register: blesh_exists
  failed_when: false
  changed_when: false

- name: Install ble.sh
  when: ansible_facts['pkg_mgr'] == "apt"
  when: blesh_exists is failed
  ansible.builtin.shell: |
    git clone --recursive --depth 1 --shallow-submodules https://github.com/akinomyoga/ble.sh.git &&
    make -C ble.sh install PREFIX=~/.local

- name: Source ble.sh
  blockinfile:
    path: ~/.bashrc
    marker: "# {mark} ANSIBLE MANAGED BLOCK - blesh"
    block: |
      source ~/.local/share/blesh/ble.sh
