- name: Check if fzf is installed
  shell: command -v fzf
  register: fzf_exists
  failed_when: false
  changed_when: false

- name: Install fzf
  when: fzf_exists is failed
  when: ansible_facts['pkg_mgr'] == "apt"
  ansible.builtin.shell: |
    git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf &&
    ~/.fzf/install

- name: Source fzf
  blockinfile:
    path: ~/.bashrc
    marker: "# {mark} ANSIBLE MANAGED BLOCK - fzf"
    block: |
      [ -f ~/.fzf.bash ] && source ~/.fzf.bash
      export FZF_DEFAULT_COMMAND='fd --type f'
