- name: Install packages with apt
  when: ansible_facts['pkg_mgr'] == "apt"
  apt:
    name:
      - build-essential
      - xclip
      - unzip
      - python-is-python3
      - feh
      - keepassxc
  become: true

# remove very old nodejs version and install a new one with snap
- name: Remove apt packages
  when: ansible_facts['pkg_mgr'] == "apt"
  apt:
    name: nodejs 
    state: absent
  become: true

# snap has newer versions of the packages
- name: Install packages with snap
  when: ansible_facts['pkg_mgr'] == "apt"
  community.general.snap:
    name:
      - cmake
      - nvim
      - node
      - htop
    classic: true
  become: true

- include_tasks: rust.yml

# cargo has latest versions of the packages
- name: Install packages with cargo
  when: ansible_facts['pkg_mgr'] == "apt"
  community.general.cargo:
    name: 
      - ripgrep
      - fd-find
      - git-delta 
  environment:
    PATH: "{{ ansible_env.HOME }}/.cargo/bin:{{ ansible_env.PATH }}"

- include_tasks: lazygit.yml
- include_tasks: fzf.yml
- include_tasks: zoxide.yml
