- name: Install packages with apt
  when: ansible_facts['pkg_mgr'] == "apt"
  apt:
    name:
      - libtraceevent-dev
      - libelf-dev
      - pkg-config
      - binutils-dev
      - libiberty-dev
      - flex
      - bison
  become: true
