- name: Check if cargo is installed
  shell: command -v cargo
  register: cargo_exists
  failed_when: false
  changed_when: false

- name: Download rustup
  when: cargo_exists is failed
  get_url:
    url: https://sh.rustup.rs
    dest: /tmp/sh.rustup.rs
    mode: '0755'
    force: 'yes'
  tags:
    - rust

- name: Install rust/cargo
  when: cargo_exists is failed
  shell: /tmp/sh.rustup.rs -y
  tags:
    - rust

- name: Source cargo
  blockinfile:
    path: ~/.bashrc
    marker: "# {mark} ANSIBLE MANAGED BLOCK - Cargo"
    block: |
      source "$HOME/.cargo/env"




