#!/bin/bash

set -e

function have {
  command -v "$1" &>/dev/null
}

# Install Ansible if not installed
if ! have ansible; then
  if have apt; then
    sudo apt-add-repository ppa:ansible/ansible
    sudo apt update
    sudo apt install ansible
  elif have pacman; then
    sudo pacman -Sy ansible
  else
    echo "Unsupported package manager"
    exit 1
  fi
  ansible-galaxy collection install community.general
fi

ansible-playbook -i hosts main.yml
